name: Auto Merge Dev -> Main -> Prod

on:
    push:
        branches:
            - dev
            

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: Configure Git
              run: |
                  git config --global user.name "github-actions"
                  git config --global user.email "github-actions@github.com"

            - name: Merge dev -> main
              run: |
                  git fetch origin
                  git checkout main
                  git pull origin main
                  git merge origin/dev --allow-unrelated-histories
                  git push origin main

            - name: Merge main -> prod
              run: |
                  git checkout prod
                  git pull origin prod
                  git merge origin/main --allow-unrelated-histories
                  git push origin prod